replicas: 1

image: "docker.elastic.co/kibana/kibana"
imageTag: "8.5.1"
imagePullPolicy: "IfNotPresent"

resources:
  requests:
    cpu: "200m"
    memory: "156Mi"
  limits:
    cpu: "250m"
    memory: "250Mi"

elasticsearchHosts: "http://elasticsearch-master:9200"
elasticsearchUsername: "elastic"
elasticsearchPassword: "elastic"

extraEnvs:
  - name: NODE_OPTIONS
    value: "--max-old-space-size=180"

protocol: http
serverHost: "0.0.0.0"
httpPort: 5601

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  periodSeconds: 10
  successThreshold: 3
  timeoutSeconds: 5

service:
  type: ClusterIP
  port: 5601

ingress:
  enabled: false
  # Uncomment and configure TLS when certs are ready:
  # tls:
  #   - secretName: kibana-tls
  #     hosts:
  #       - kibana.erickyc.store
