# values.yaml for kube-prometheus-stack
global:
  rbac:
    create: true

kubePrometheusStack:
  enabled: true

defaultRules:
  create: true
  rules:
    etcd: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false

prometheus:
  enabled: true
  prometheusSpec:
    retention: 1d
    scrapeInterval: 30s
    evaluationInterval: 30s
    resources:
      requests:
        cpu: 100m
        memory: 150Mi
      limits:
        cpu: 150m
        memory: 200Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
  service:
    type: ClusterIP
    port: 9090
    annotations: {}
  ingress:
    enabled: false

grafana:
  enabled: true
  adminPassword: admin
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 110Mi
  service:
    type: ClusterIP
    port: 3000
  ingress:
    enabled: false
  grafana.ini:
    server:
      serve_from_sub_path: true
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki.default.svc.cluster.local:3100
          isDefault: false
          jsonData:
            maxLines: 1000


alertmanager:
  enabled: true
  alertmanagerSpec:
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
      limits:
        cpu: 100m
        memory: 110Mi
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 1Gi
  service:
    type: ClusterIP
    port: 9093
  ingress:
    enabled: false

kubeApiServer:
  enabled: true

kubeControllerManager:
  enabled: false

coreDns:
  enabled: true

kubeScheduler:
  enabled: false

kubeProxy:
  enabled: true

nodeExporter:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 110Mi

kubeStateMetrics:
  enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 110Mi

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 110Mi

# Loki configuration
loki:
  enabled: true
  isDefault: false
  persistence:
    enabled: true
    size: 1Gi
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 110Mi

# Promtail configuration
promtail:
  enabled: true
  serviceMonitor:
    enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 110Mi
